sudo: required
language: python
python: '3.7.3'

install: apt-get install docker

before_script: docker build . -t iris

with_content_shell: true

# Job sections
jobs:
  include:
    - stage: Lint
      before_install: skip
      before_script: skip
      install: pip install tox
      script: tox -e flake8
    - stage: Ubuntu 16.04 Image search and mouse movement tests
      os: linux
      dist: xenial
      script:
        - docker run -i -t iris /bin/bash
        - iris -h

# Email notification
notifications:
  email:
    recipients:
      - twalker@mozilla.com
      - mwobensmith@mozilla.com
    on_success: change
    on_failure: always
    on_cancel: always
